const enCountries = {
  Afghanistan: "أفغانستان",
  "Åland Islands": "جزر أولاند",
  Albania: "ألبانيا",
  Algeria: "الجزائر",
  "American Samoa": "ساموا الأمريكية",
  Andorra: "أندورا",
  Angola: "أنغولا",
  Anguilla: "أنغويلا",
  Antarctica: "القطب الجنوبي",
  "Antigua And Barbuda": "أنتيغوا وبربودا",
  Argentina: "الأرجنتين",
  Armenia: "أرمينيا",
  Aruba: "أروبا",
  "Ascension Island": "جزيرة الأسينشين",
  Australia: "أستراليا",
  Austria: "النمسا",
  Azerbaijan: "أذربيجان",
  Bahamas: "باهاماس",
  Bahrain: "البحرين",
  Bangladesh: "بنغلاديش",
  Barbados: "بربادوس",
  Belarus: "بيلاروسيا",
  Belgium: "بلجيكا",
  Belize: "بليز",
  Benin: "بنين",
  Bermuda: "برمودا",
  Bhutan: "بوتان",
  "Bolivia, Plurinational State Of": "بوليفيا",
  "Bonaire, Saint Eustatius And Saba": "بونير، سانت أوستاتيوس وسابا",
  "Bosnia & Herzegovina": "البوسنة والهرسك",
  Botswana: "بوتسوانا",
  Brazil: "البرازيل",
  "British Indian Ocean Territory": "إقليم المحيط الهندي البريطاني",
  "Brunei Darussalam": "بروناي دار السلام",
  Bulgaria: "بلغاريا",
  "Burkina Faso": "بوركينا فاسو",
  Burundi: "بوروندي",
  "Cabo Verde": "الرأس الأخضر",
  Cambodia: "كمبوديا",
  Cameroon: "الكاميرون",
  Canada: "كندا",
  "Cayman Islands": "جزر كايمان",
  "Central African Republic": "جمهورية أفريقيا الوسطى",
  Chad: "تشاد",
  Chile: "تشيلي",
  China: "الصين",
  "Christmas Island": "جزيرة الكريسماس",
  "Cocos (Keeling) Islands": "جزر كوكوس (كيلينغ)",
  Colombia: "كولومبيا",
  Comoros: "جزر القمر",
  "Cook Islands": "جزر كوك",
  "Costa Rica": "كوستاريكا",
  "Côte d'Ivoire": "ساحل العاج",
  Croatia: "كرواتيا",
  Cuba: "كوبا",
  Curacao: "كوراساو",
  Cyprus: "قبرص",
  "Czech Republic": "جمهورية التشيك",
  "Democratic Republic Of Congo": "جمهورية الكونغو الديمقراطية",
  Denmark: "الدنمارك",
  Djibouti: "جيبوتي",
  Dominica: "دومينيكا",
  "Dominican Republic": "جمهورية الدومينيكان",
  Ecuador: "الإكوادور",
  Egypt: "مصر",
  "El Salvador": "السلفادور",
  "Equatorial Guinea": "غينيا الاستوائية",
  Eritrea: "إريتريا",
  Estonia: "إستونيا",
  Ethiopia: "إثيوبيا",
  "European Union": "الاتحاد الأوروبي",
  "Falkland Islands": "جزر فوكلاند",
  "Faroe Islands": "جزر فارو",
  Fiji: "فيجي",
  Finland: "فنلندا",
  France: "فرنسا",
  "France, Metropolitan": "فرنسا الحضرية",
  "French Guiana": "غويانا الفرنسية",
  "French Polynesia": "بولينيزيا الفرنسية",
  Gabon: "الغابون",
  Gambia: "غامبيا",
  Georgia: "جورجيا",
  Germany: "ألمانيا",
  Ghana: "غانا",
  Gibraltar: "جبل طارق",
  Greece: "اليونان",
  Greenland: "غرينلاند",
  Grenada: "غرينادا",
  Guadeloupe: "غوادلوب",
  Guam: "غوام",
  Guatemala: "غواتيمالا",
  Guernsey: "غيرنسي",
  Guinea: "غينيا",
  "Guinea-bissau": "غينيا بيساو",
  Guyana: "غويانا",
  Haiti: "هايتي",
  Honduras: "هندوراس",
  "Hong Kong": "هونغ كونغ",
  Hungary: "المجر",
  Iceland: "أيسلندا",
  India: "الهند",
  Indonesia: "إندونيسيا",
  "Iran, Islamic Republic Of": "إيران",
  Iraq: "العراق",
  Ireland: "أيرلندا",
  "Isle Of Man": "جزيرة مان",
  Israel: "إسرائيل",
  Italy: "إيطاليا",
  Jamaica: "جامايكا",
  Japan: "اليابان",
  Jersey: "جيرسي",
  Jordan: "الأردن",
  Kazakhstan: "كازاخستان",
  Kenya: "كينيا",
  Kiribati: "كيريباتي",
  "Korea, Democratic People's Republic Of": "كوريا الشمالية",
  "Korea, Republic Of": "كوريا الجنوبية",
  Kuwait: "الكويت",
  Kyrgyzstan: "قيرغيزستان",
  "Lao People's Democratic Republic": "لاوس",
  Latvia: "لاتفيا",
  Lebanon: "لبنان",
  Lesotho: "ليسوتو",
  Liberia: "ليبيريا",
  Libya: "ليبيا",
  Liechtenstein: "ليختنشتاين",
  Lithuania: "ليتوانيا",
  Luxembourg: "لوكسمبورغ",
  Macao: "ماكاو",
  "Macedonia, The Former Yugoslav Republic Of": "مقدونيا",
  Madagascar: "مدغشقر",
  Malawi: "مالاوي",
  Malaysia: "ماليزيا",
  Maldives: "المالديف",
  Mali: "مالي",
  Malta: "مالطا",
  "Marshall Islands": "جزر مارشال",
  Martinique: "مارتينيك",
  Mauritania: "موريتانيا",
  Mauritius: "موريشيوس",
  Mayotte: "مايوت",
  Mexico: "المكسيك",
  "Micronesia, Federated States Of": "ولايات ميكرونيزيا الفيدرالية",
  Moldova: "مولدوفا",
  Monaco: "موناكو",
  Mongolia: "منغوليا",
  Montenegro: "مونتينيغرو",
  Montserrat: "مونتسرات",
  Morocco: "المغرب",
  Mozambique: "موزمبيق",
  Myanmar: "ميانمار",
  Namibia: "ناميبيا",
  Nauru: "ناورو",
  Nepal: "نيبال",
  Netherlands: "هولندا",
  "New Caledonia": "كاليدونيا الجديدة",
  "New Zealand": "نيوزيلندا",
  Nicaragua: "نيكاراغوا",
  Niger: "النيجر",
  Nigeria: "نيجيريا",
  Niue: "نيوي",
  "Norfolk Island": "جزيرة نورفولك",
  "Northern Mariana Islands": "جزر ماريانا الشمالية",
  Norway: "النرويج",
  Oman: "عمان",
  Pakistan: "باكستان",
  Palau: "بالاو",
  "Palestinian Territory, Occupied": "الأراضي الفلسطينية المحتلة",
  Panama: "بنما",
  "Papua New Guinea": "بابوا غينيا الجديدة",
  Paraguay: "باراغواي",
  Peru: "بيرو",
  Philippines: "الفلبين",
  Pitcairn: "بيتكيرن",
  Poland: "بولندا",
  Portugal: "البرتغال",
  "Puerto Rico": "بورتو ريكو",
  Qatar: "قطر",
  "Republic Of Congo": "جمهورية الكونغو",
  Reunion: "ريونيون",
  Romania: "رومانيا",
  "Russian Federation": "الاتحاد الروسي",
  Rwanda: "رواندا",
  "Saint Barthélemy": "سانت بارتيلمي",
  "Saint Helena, Ascension And Tristan Da Cunha":
    "سانت هيلينا، أسينشين و تريستان دا كونا",
  "Saint Kitts And Nevis": "سانت كيتس ونيفيس",
  "Saint Lucia": "سانت لوسيا",
  "Saint Martin": "سانت مارتن",
  "Saint Pierre And Miquelon": "سان بيير وميكلون",
  "Saint Vincent And The Grenadines": "سانت فينسنت والغرينادين",
  Samoa: "ساموا",
  "San Marino": "سان مارينو",
  "Sao Tome and Principe": "ساو تومي وبرينسيبي",
  "Saudi Arabia": "المملكة العربية السعودية",
  Senegal: "السنغال",
  Serbia: "صربيا",
  Seychelles: "سيشيل",
  "Sierra Leone": "سيراليون",
  Singapore: "سنغافورة",
  "Sint Maarten": "سينت مارتن",
  Slovakia: "سلوفاكيا",
  Slovenia: "سلوفينيا",
  "Solomon Islands": "جزر سليمان",
  Somalia: "الصومال",
  "South Africa": "جنوب أفريقيا",
  "South Sudan": "جنوب السودان",
  Spain: "إسبانيا",
  "Sri Lanka": "سريلانكا",
  Sudan: "السودان",
  Suriname: "سورينام",
  "Svalbard And Jan Mayen": "سفالبارد وجزر جان ماي تن",
  Swaziland: "سوازيلاند",
  Sweden: "السويد",
  Switzerland: "سويسرا",
  "Syrian Arab Republic": "الجمهورية العربية السورية",
  Taiwan: "تايوان",
  Tajikistan: "طاجيكستان",
  "Tanzania, United Republic Of": "تنزانيا",
  Thailand: "تايلاند",
  "Timor-Leste, Democratic Republic of": "تيمور الشرقية",
  Togo: "توغو",
  Tokelau: "توكيلاو",
  Tonga: "تونغا",
  "Trinidad And Tobago": "ترينيداد وتوباغو",
  "Tristan de Cunha": "تريستان دا كونا",
  Tunisia: "تونس",
  Turkey: "تركيا",
  Turkmenistan: "تركمانستان",
  "Turks And Caicos Islands": "جزر تركس وكايكوس",
  Tuvalu: "توفالو",
  Uganda: "أوغندا",
  Ukraine: "أوكرانيا",
  "United Arab Emirates": "الإمارات العربية المتحدة",
  "United Kingdom": "المملكة المتحدة",
  "United States": "الولايات المتحدة",
  "United States Minor Outlying Islands": "جزر الولايات المتحدة الخارجية",
  Uruguay: "أوروغواي",
  Uzbekistan: "أوزبكستان",
  Vanuatu: "فانواتو",
  "Venezuela (Bolivarian Republic of)": "فنزويلا",
  "Viet Nam": "فيتنام",
  "Wallis And Futuna": "واليس وفوتونا",
  "Western Sahara": "الصحراء الغربية",
  Yemen: "اليمن",
  Zambia: "زامبيا",
  Zimbabwe: "زيمبابوي",
};

const arCountries = {
  إثيوبيا: "Ethiopia",
  أذربيجان: "Azerbaijan",
  أرمينيا: "Armenia",
  أروبا: "Aruba",
  إريتريا: "Eritrea",
  إسبانيا: "Spain",
  أستراليا: "Australia",
  إستونيا: "Estonia",
  إسرائيل: "Israel",
  أفغانستان: "Afghanistan",
  "إقليم المحيط الهندي البريطاني": "British Indian Ocean Territory",
  "الاتحاد الأوروبي": "European Union",
  "الاتحاد الروسي": "Russian Federation",
  "الأراضي الفلسطينية المحتلة": "Palestinian Territory, Occupied",
  الأرجنتين: "Argentina",
  الأردن: "Jordan",
  الإكوادور: "Ecuador",
  "الإمارات العربية المتحدة": "United Arab Emirates",
  ألبانيا: "Albania",
  البحرين: "Bahrain",
  البرازيل: "Brazil",
  البرتغال: "Portugal",
  "البوسنة والهرسك": "Bosnia & Herzegovina",
  الجزائر: "Algeria",
  "الجمهورية العربية السورية": "Syrian Arab Republic",
  الدنمارك: "Denmark",
  "الرأس الأخضر": "Cabo Verde",
  السلفادور: "El Salvador",
  السنغال: "Senegal",
  السودان: "Sudan",
  السويد: "Sweden",
  "الصحراء الغربية": "Western Sahara",
  الصومال: "Somalia",
  الصين: "China",
  العراق: "Iraq",
  الغابون: "Gabon",
  الفلبين: "Philippines",
  "القطب الجنوبي": "Antarctica",
  الكاميرون: "Cameroon",
  الكويت: "Kuwait",
  المالديف: "Maldives",
  ألمانيا: "Germany",
  المجر: "Hungary",
  المغرب: "Morocco",
  المكسيك: "Mexico",
  "المملكة العربية السعودية": "Saudi Arabia",
  "المملكة المتحدة": "United Kingdom",
  النرويج: "Norway",
  النمسا: "Austria",
  النيجر: "Niger",
  الهند: "India",
  "الولايات المتحدة": "United States",
  اليابان: "Japan",
  اليمن: "Yemen",
  اليونان: "Greece",
  "أنتيغوا وبربودا": "Antigua And Barbuda",
  أندورا: "Andorra",
  إندونيسيا: "Indonesia",
  أنغولا: "Angola",
  أنغويلا: "Anguilla",
  أوروغواي: "Uruguay",
  أوزبكستان: "Uzbekistan",
  أوغندا: "Uganda",
  أوكرانيا: "Ukraine",
  إيران: "Iran, Islamic Republic Of",
  أيرلندا: "Ireland",
  أيسلندا: "Iceland",
  إيطاليا: "Italy",
  "بابوا غينيا الجديدة": "Papua New Guinea",
  باراغواي: "Paraguay",
  باكستان: "Pakistan",
  بالاو: "Palau",
  باهاماس: "Bahamas",
  بربادوس: "Barbados",
  برمودا: "Bermuda",
  "بروناي دار السلام": "Brunei Darussalam",
  بلجيكا: "Belgium",
  بلغاريا: "Bulgaria",
  بليز: "Belize",
  بنغلاديش: "Bangladesh",
  بنما: "Panama",
  بنين: "Benin",
  بوتان: "Bhutan",
  بوتسوانا: "Botswana",
  "بورتو ريكو": "Puerto Rico",
  "بوركينا فاسو": "Burkina Faso",
  بوروندي: "Burundi",
  بولندا: "Poland",
  بوليفيا: "Bolivia, Plurinational State Of",
  "بولينيزيا الفرنسية": "French Polynesia",
  "بونير، سانت أوستاتيوس وسابا": "Bonaire, Saint Eustatius And Saba",
  بيتكيرن: "Pitcairn",
  بيرو: "Peru",
  بيلاروسيا: "Belarus",
  تايلاند: "Thailand",
  تايوان: "Taiwan",
  تركمانستان: "Turkmenistan",
  تركيا: "Turkey",
  "تريستان دا كونا": "Tristan de Cunha",
  "ترينيداد وتوباغو": "Trinidad And Tobago",
  تشاد: "Chad",
  تشيلي: "Chile",
  تنزانيا: "Tanzania, United Republic Of",
  توغو: "Togo",
  توفالو: "Tuvalu",
  توكيلاو: "Tokelau",
  تونس: "Tunisia",
  تونغا: "Tonga",
  "تيمور الشرقية": "Timor-Leste, Democratic Republic of",
  جامايكا: "Jamaica",
  "جبل طارق": "Gibraltar",
  "جزر القمر": "Comoros",
  "جزر الولايات المتحدة الخارجية": "United States Minor Outlying Islands",
  "جزر أولاند": "Åland Islands",
  "جزر تركس وكايكوس": "Turks And Caicos Islands",
  "جزر سليمان": "Solomon Islands",
  "جزر فارو": "Faroe Islands",
  "جزر فوكلاند": "Falkland Islands",
  "جزر فيرجن الأمريكية": "Virgin Islands (US)",
  "جزر فيرجن البريطانية": "Virgin Islands (British)",
  "جزر كايمان": "Cayman Islands",
  "جزر كوك": "Cook Islands",
  "جزر كوكوس (كيلينغ)": "Cocos (Keeling) Islands",
  "جزر مارشال": "Marshall Islands",
  "جزر ماريانا الشمالية": "Northern Mariana Islands",
  "جزيرة الأسينشين": "Ascension Island",
  "جزيرة الكريسماس": "Christmas Island",
  "جزيرة مان": "Isle Of Man",
  "جزيرة نورفولك": "Norfolk Island",
  "جمهورية أفريقيا الوسطى": "Central African Republic",
  "جمهورية التشيك": "Czech Republic",
  "جمهورية الدومينيكان": "Dominican Republic",
  "جمهورية الكونغو": "Republic Of Congo",
  "جمهورية الكونغو الديمقراطية": "Democratic Republic Of Congo",
  "جنوب أفريقيا": "South Africa",
  "جنوب السودان": "South Sudan",
  جورجيا: "Georgia",
  جيبوتي: "Djibouti",
  جيرسي: "Jersey",
  "دولة الفاتيكان": "Vatican City State",
  دومينيكا: "Dominica",
  رواندا: "Rwanda",
  رومانيا: "Romania",
  ريونيون: "Reunion",
  زامبيا: "Zambia",
  زيمبابوي: "Zimbabwe",
  "ساحل العاج": "Côte d'Ivoire",
  ساموا: "Samoa",
  "ساموا الأمريكية": "American Samoa",
  "سان بيير وميكلون": "Saint Pierre And Miquelon",
  "سان مارينو": "San Marino",
  "سانت بارتيلمي": "Saint Barthélemy",
  "سانت فينسنت وجزر غرينادين": "Saint Vincent And The Grenadines",
  "سانت كيتس ونيفيس": "Saint Kitts And Nevis",
  "سانت لوسيا": "Saint Lucia",
  "سانت مارتن": "Saint Martin",
  "سانت هيلينا، أسينشين و تريستان دا كونا":
    "Saint Helena, Ascension And Tristan Da Cunha",
  "ساو تومي وبرينسيبي": "Sao Tome and Principe",
  سريلانكا: "Sri Lanka",
  "سفالبارد وجزر جان ماي تن": "Svalbard And Jan Mayen",
  سلوفاكيا: "Slovakia",
  سلوفينيا: "Slovenia",
  سنغافورة: "Singapore",
  سوازيلاند: "Swaziland",
  سورينام: "Suriname",
  سويسرا: "Switzerland",
  سيراليون: "Sierra Leone",
  سيشيل: "Seychelles",
  "سينت مارتن": "Sint Maarten",
  صربيا: "Serbia",
  طاجيكستان: "Tajikistan",
  عمان: "Oman",
  غامبيا: "Gambia",
  غانا: "Ghana",
  غرينادا: "Grenada",
  غرينلاند: "Greenland",
  غواتيمالا: "Guatemala",
  غوادلوب: "Guadeloupe",
  غوام: "Guam",
  غويانا: "Guyana",
  "غويانا الفرنسية": "French Guiana",
  غيرنسي: "Guernsey",
  غينيا: "Guinea",
  "غينيا الاستوائية": "Equatorial Guinea",
  "غينيا بيساو": "Guinea-bissau",
  فانواتو: "Vanuatu",
  فرنسا: "France",
  "فرنسا الحضرية": "France, Metropolitan",
  فنزويلا: "Venezuela, Bolivarian Republic Of",
  فنلندا: "Finland",
  فيتنام: "Viet Nam",
  فيجي: "Fiji",
  قبرص: "Cyprus",
  قطر: "Qatar",
  قيرغيزستان: "Kyrgyzstan",
  كازاخستان: "Kazakhstan",
  "كاليدونيا الجديدة": "New Caledonia",
  كرواتيا: "Croatia",
  كمبوديا: "Cambodia",
  كندا: "Canada",
  كوبا: "Cuba",
  كوراساو: "Curacao",
  "كوريا الجنوبية": "Korea, Republic Of",
  "كوريا الشمالية": "Korea, Democratic People's Republic Of",
  كوستاريكا: "Costa Rica",
  كوسوفو: "Kosovo",
  كولومبيا: "Colombia",
  كيريباتي: "Kiribati",
  كينيا: "Kenya",
  لاتفيا: "Latvia",
  لاوس: "Lao People's Democratic Republic",
  لبنان: "Lebanon",
  لوكسمبورغ: "Luxembourg",
  ليبيا: "Libya",
  ليبيريا: "Liberia",
  ليتوانيا: "Lithuania",
  ليختنشتاين: "Liechtenstein",
  ليسوتو: "Lesotho",
  مارتينيك: "Martinique",
  ماكاو: "Macao",
  مالاوي: "Malawi",
  مالطا: "Malta",
  مالي: "Mali",
  ماليزيا: "Malaysia",
  مايوت: "Mayotte",
  مدغشقر: "Madagascar",
  مصر: "Egypt",
  مقدونيا: "Macedonia, The Former Yugoslav Republic Of",
  منغوليا: "Mongolia",
  موريتانيا: "Mauritania",
  موريشيوس: "Mauritius",
  موزمبيق: "Mozambique",
  مولدوفا: "Moldova",
  موناكو: "Monaco",
  مونتسرات: "Montserrat",
  مونتينيغرو: "Montenegro",
  ميانمار: "Myanmar",
  ناميبيا: "Namibia",
  ناورو: "Nauru",
  نيبال: "Nepal",
  نيجيريا: "Nigeria",
  نيكاراغوا: "Nicaragua",
  نيوزيلندا: "New Zealand",
  نيوي: "Niue",
  هايتي: "Haiti",
  هندوراس: "Honduras",
  هولندا: "Netherlands",
  "هونغ كونغ": "Hong Kong",
  "واليس وفوتونا": "Wallis And Futuna",
  "ولايات ميكرونيزيا الفيدرالية": "Micronesia, Federated States Of",
};

const getCountries = (locale) => {
  return locale === "ar" ? arCountries : enCountries;
};

export default getCountries;
